<?php
/**
 * Created by IntelliJ IDEA.
 * User: Jake
 * Date: 03/03/2018
 * Time: 18:08
 */

namespace api\modules\v1;



class Module extends \yii\base\Module {

    public $controllerNamespace = 'api\modules\v1\controllers';

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
    }

}