<?php
/**
 * Created by IntelliJ IDEA.
 * User: Jake
 * Date: 03/03/2018
 * Time: 19:09
 */

namespace api\modules\v1\controllers;

use common\helpers\Mailer;
use Yii;
use yii\rest\ActiveController;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\QueryParamAuth;
use yii\data\ActiveDataProvider;
use yii\web\Response;

class SiteController extends \yii\rest\ActiveController {


    public $modelClass = 'api\modules\v1\models\Admin';

    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items',
    ];

    public function behaviors() {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['contentNegotiator']['formats']['text/html'] = Response::FORMAT_JSON;
        return $behaviors;
    }

    public function actions() {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index'], $actions['update'], $actions['create'], $actions['delete'], $actions['view']);
        return $actions;
    }


    public function actionIndex() {
        $session = Yii::$app->session;

        var_dump('<pre>', Mailer::registerCheckDigit("272746238@qq.com", "fjdsafa13"), '</pre>');
        exit();

        //var_dump('<pre>', $session, '</pre>');

        //$session->set("aaaa", "aaaaaa");
//        if($session->get("aaaa") === "aaaaaa") {
//            var_dump('<pre>', "aaaaaa!", $_SESSION, '</pre>');
//        } else {
//            var_dump('<pre>', "____aaaaaa____!", '</pre>');
//        }
        $modelClass = $this->modelClass;
        $query = $modelClass::find();
        //return $query;
        $query->where(["id" => 1]);
//        var_dump(Yii::$app->redis->get("cc"));
        Yii::$app->redis->set("cc", "ddddddd");
//        var_dump(Yii::$app->redis->get("cc"));
        //var_dump($query);
//        return [
//            'err' => true,
//            'status' => 100,
//            'data' => [
//                'aaa' => '1111',
//                'bbb' => '2222',
//            ],
//        ];
        return new ActiveDataProvider([
            'query' => $query
        ]);
    }

    public function checkAccess($action, $model = null, $params = [])
    {
        //parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
    }

}